apiVersion: batch/v1
kind: Job
metadata:
  name: webregi-collectstatic
spec:
  template:
    spec:
      containers:
        - name: webregi-v2-app
          image: regiapriandi012/bismillah-webregi-v2-final-deploykube:latest
          command: ['python', 'manage.py', 'collectstatic']
          env:
            - name: DATABASE_USER
              value: "postgres"
            - name: DATABASE_PASSWORD
              value: "postgres"
            - name: DATABASE_HOST
              value: "db"
            - name: DATABASE_NAME
              value: "postgres"
      restartPolicy: Never
  backoffLimit: 5

